add: config.toml(workspace-trust), mpd config/run/sticker/database, pythonrc, tmux.conf(join table & bindings), wezterm.lua(key tables & resurrect plugin), languages.toml(idris grammar); fix: config.toml(key bindings and formatting), languages.toml(lsp configs and quoting), tmux.conf(bindings and history limit), wezterm.lua(color scheme and status), aliases.zsh(alias definitions), functions.zsh(function definitions); rm: config.toml(insecure flag), tmux.conf(unbound keys), wezterm.lua(commented config management); update: .gitignore(patterns), .profile(path/dedup), .zshenv(env vars/paths), aliases.zsh(fzf/sk aliases), completions.zsh(bashcompinit), functions.zsh(assorted functions), deploy-headless.sh(user creation), deploy-void.zsh(packages), .tmux.conf(keybindings), .wezterm.lua(keybindings), aliases.zsh(fzf aliases);

diff --git a/scripts/clone b/scripts/clone
--- a/scripts/clone
+++ b/scripts/clone
@@ -1,8 +1,120 @@
-#!/bin/env sh
+#!/bin/env zsh
+
+# repository cloner
 
 set -eu
 
-cmd="$(basename "$0")"
+self="$(basename "$0")"
+desc="$(cat "$0" | head -3 | tail -1 | sed 's:^\s*::')"
+
+error() {
+	printf '%s:' "$self" >&2
+	printf ' %s' $@ >&2
+	printf '\n' >&2
+}
+
+fatal() {
+	error "$@"
+	exit 1
+}
+
+clone_dir="${CLONES:-$PWD}"
+owner="${SUDO_USER:-$(logname)}"
+host="github"
+deep=false
+
+# echo "\$PWD: $PWD" >>/tmp/clone.debug
+# echo "\$(pwd): $(pwd)" >>/tmp/clone.debug
+# echo "\$clone_dir: $clone_dir" >>/tmp/clone.debug
+
+typeset -A host_commands=(
+	[darcs]=darcs
+	[github]=git
+	[tilde]=git
+	[srht]=git
+	[gitlab]=git
+	[codeberg]=git
+	[freedesktop]=git
+)
+
+typeset -A host_urls=(
+	[darcs]=https://hub.darcs.net
+	[github]=https://github.com
+	[tilde]=https://tildegit.com
+	[srht]=https://sr.ht
+	[gitlab]=https://gitlab.com
+	[codeberg]=https://codeberg.org
+	[freedesktop]=https://gitlab.freedesktop.org
+)
+
+typeset -A depths=(
+	[darcs]=--lazy
+	[git]=--depth=1
+)
+
+hosts1="${(k)host_commands[@]}"
+hosts2="${(k)host_urls[@]}"
+
+[ "${hosts1}" = "${hosts2}" ] || fatal internal: host urls disagree with commands
+
+hosts="${hosts1[@]}"
+
+command -v bat &>/dev/null || bat() { less --tilde -F; }
+
+help_info() {
+	cat <<-eof | bat -lman
+		usage: $self [FLAG]... [REPO]...
+
+		$desc
+
+		flags:
+		  -h, --help             print this message and exit
+		  -c, --clone-dir        directory to keep clone(s) in ${clone_dir:+(default: $clone_dir)}
+		  -d, --deep             clone a repository deeply instead of a shallowly
+		  -o, --owner            name of the developer (for cases where none can be parsed from the elements) ${owner:+(default: $owner)}
+		  -r, --repo-host        name of the host to query for the repo (default: $host) (options: $hosts)
+
+	eof
+	(($#)) || fatal internal: help exit code unspecified
+	exit $1
+}
+
+repos=()
+
+while (($#)); do
+	case "$1" in
+		-h* | --help) help_info 0 ;;
+		-d | --deep) deep=true ;;
+		-d*)
+			deep=true
+			argv[1]="-${1##-d}"
+			continue
+			;;
+		-r | --repo-host)
+			host="$2"
+			shift
+			;;
+		-r*)
+			host="${1##-r}"
+			;;
+		-o | --owner)
+			owner="$2"
+			shift
+			;;
+		-o*) owner="${1##-o}" ;;
+		-c | --clone-dir)
+			clone_dir="$2"
+			shift
+			;;
+		-c*) clone_dir="${1##-c}" ;;
+		*) repos+=("$1") ;;
+	esac
+	shift
+done
+
+((${#repos})) || fatal no repositories specified
+
+set -- "${repos[@]}"
 
 slashed() {
 	case "$1" in
@@ -12,48 +124,51 @@ slashed() {
 }
 
 take() {
-	$(command -v mkdir) -p "$1" || return $?
+	command mkdir -p "$1"
 	cd "$1"
 }
 
-# goto() {
-# 	cd "$1" || return $?
-# 	echo "$1"
+# depth="--depth=1"
+# dev=""
+
+# [ "$1" = "-d" ] && {
+# 	depth=""
+# 	shift 1
 # }
 
-[ $# -eq 0 ] && {
-	echo "$cmd: no args received" >&2
-	return 1
-}
+# slashed "$dev" || {
+# 	owner="$1"
+# 	shift 1
+# }
 
-depth="--depth=1"
-dev=""
+# args="$*"
+# [ $# -eq 0 ] && {
+# 	args="$args $owner"
+# 	owner="$USER"
+# }
 
-[ "$1" = "-d" ] && {
-	depth=""
-	shift 1
-}
+depth='' # due to strictness
+$deep || depth="$depths[$host_commands[$host]]"
 
-slashed "$dev" || {
-	dev="$1"
-	shift 1
-}
+cmd=$host_commands[$host]
+url=$host_urls[$host]
 
-args="$*"
-[ $# -eq 0 ] && {
-	args="$args $dev"
-	dev="$USER"
-}
-
-echo "$args" | while read repo; do
+for repo in "$@"; do
+	_url=''
+	case "$repo" in
+		http://* | https://* | ssh://*) _url="$(sed 's%^\w+://\w+(\.\w)+%%' <<<"$repo")" ;;
+		*) _url="$url" ;;
+	esac
+	local dev=''
 	slashed "$repo" && dev="$(basename "$(dirname "$repo")")"
-	repo=$(basename "$repo")
-	pth="$CLONEDIR/$dev/$repo"
+	[ -n "$dev" ] || dev="$owner"
+	repo="$(basename "$repo")"
+	pth="$clone_dir/$dev/$repo"
 	if [ -d "$pth" ]; then
-		echo "$cmd: already have $dev/$repo" >&2
+		error "already have $dev/$repo"
 	else
-		echo "$cmd: fetching $dev/$repo" >&2
-		take "$CLONEDIR/$dev" && git clone $depth "$REPO_HOST/$dev/$repo" "$repo" >&2
+		error "fetching $dev/$repo" # using error instead of echo so that only directory names are printed to stdout which lets wrappers easily navigate into the right directory
+		take "$clone_dir/$dev" && $cmd clone $depth "$_url/$dev/$repo" "$repo" >&2
 	fi
 	echo "$pth"
 done
diff --git a/scripts/fetch b/scripts/fetch
--- a/scripts/fetch
+++ b/scripts/fetch
@@ -1,100 +1,143 @@
 #!/bin/sh
 
-# a chached downloader, initially written for ghs with the future in mind.
-
-self=$(basename "$ZSH_ARGZERO")
+# a POSIX compliant chacher/downloader, initially written for kendfss/ghs with the future in mind.
 
 set -eu
 testing=false
 [ $testing = true ] && set -x
 
-helpText() {
-	cat <<-EOF
-		usage: $self [OPTION]... [URL]...
-		     a script for caching file downloads
+self=$(basename "$0")
+desc="$(cat "$0" | head -3 | tail -1 | sed -E 's:^#\s*::')"
 
-		  flags:
-		     -c, --command   command to use when downloading files
-		                     default: just a plain curl with the '-o' for naming and -L to follow redirects
-		     -d, --directory use the given directory as a cache (it won't be created for you)
-		                     default: .
-		     -r, --read      read file contents to stdout after downloading
-
-		  file names will be stripped of slashes and colons by replacing them with hyphens and
-		  then trimming sequences of repeated hyphens
-	EOF
-}
-
-need() {
-	while [ $# -gt 0 ]; do
-		[ -x "$(command -v "$1")" ] || {
-			echo "$self: couldn't find $1" >&2
-			return 1
-		}
-		shift
-	done
-}
-
-need curl || exit $?
+command -v bat >/dev/null 2>/dev/null || bat() { less; }
 
 dir='.'
 cmd=''
 read=false
-
+cont=false
+based=false
 args=''
 SEP="£"
+
+help_text() {
+	cat <<-EOF | bat -lman
+		usage: $self [OPTION]... [URL]...
+
+		$desc
+
+		flags:
+		   -C, --continue  continue download from earlier (only works with curl)
+		   -b, --based     always use basename of the url as the file's name
+		   -c, --command   command to use when downloading files. expected to download file to stdout (default: curl -L)
+		   -d, --directory use the given directory as a cache (it won't be created for you) (default: $dir)
+		   -h, --help      print this message and exit
+		   -r, --read      read file contents to stdout after downloading
+
+		file names will be stripped of slashes and colons by replacing them with hyphens and
+		then trimming sequences of repeated hyphens
+	EOF
+	[ $# -gt 0 ] || exit 1
+	# shellcheck disable=SC2086
+	exit $1
+}
+
+need() {
+	while [ $# -gt 0 ]; do
+		[ -x "$(command -v "$1")" ] || fatal "couldn't find $1"
+		shift
+	done
+}
+
+fatal() {
+	error "$@"
+	exit 1
+}
+
+error() {
+	printf '%s:' "$self" >&2
+	# shellcheck disable=SC2068
+	printf ' %s' $@ >&2
+	echo >&2
+}
+
+need curl
 
 while [ $# -gt 0 ]; do
 	case "$1" in
 		-d | --dir)
 			dir="$2"
-			shift 2
+			shift
 			;;
 		-c | --command | command)
 			cmd="$2"
-			shift 2
+			shift
 			;;
 		-r | --read | read)
 			read=true
-			shift
 			;;
-		-rd | rd)
-			read=true
-			dir="$2"
-			shift 2
-			;;
-		-rc | rc)
-			read=true
-			cmd="$2"
-			shift 2
-			;;
+		-C | --continue | continue) cont=true ;;
+		-b | --based | based) based=true ;;
 		-h | --help | help)
-			helpText
-			exit 0
+			help_text 0
 			;;
 		-)
 			args="$args$SEP$(p)"
 			shift
 			;;
 		-*)
-			echo "unrecognized flag '$1'" >&2
-			helpText >&2
-			exit 1
+			hasd="$(printf '%s' "$1" | sed 's:[^d]::g')"
+			hasc="$(printf '%s' "$1" | sed 's:[^c]::g')"
+			if [ ${#hasd} = 0 ] || [ ${#hasc} = 0 ]; then
+				:
+			else
+				fatal abbreviated flag cannot contain b and c
+			fi
+			while read -r char; do
+				case "$char" in
+					r) read=true ;;
+					c)
+						cmd="$2"
+						shift
+						;;
+					C) cont=true ;;
+					d)
+						dir="$2"
+						shift
+						;;
+					b) based=true ;;
+					h) help_text 0 ;;
+					*)
+						error unsupported flag: "'$char'" in "'$1'"
+						help_text 1
+						;;
+				esac
+			done <<-EOF
+				$(printf '%s' "$1" | sed 's:^-::;s:.:&\n:g')
+			EOF
 			;;
 		*)
 			args="$args$SEP$1"
 			shift
 			;;
 	esac
+	[ $# -gt 0 ] && shift
 done
 
-[ "${#args}" = 0 ] && echo "$self: no args received. use '-' to read from clipboard" >&2 && exit 1
+[ "${#args}" = 0 ] && fatal "no args received. use '-' to read from clipboard"
+
+curl() {
+	if [ $cont = true ]; then
+		command curl -LC - "$@"
+	else
+		command curl "$@"
+	fi
+}
 
 get() {
 	arg="$1"
 	name="$2"
 	if [ -z "$cmd" ]; then
-		curl -L "$arg" -o "$name"
+		curl "$arg" -o "$name" >&2
 	else
 		eval "$cmd \"\$arg\"" >"$name"
 	fi
@@ -102,10 +145,14 @@ get() {
 
 load() {
 	for link in "$@"; do
-		name="$dir/$(echo "$link" | sed -E 's|^\w+://||g;s|[/:]|-|g;s:-+:-:g;s:-$::g')"
+		if [ $based = false ]; then
+			name="$dir/$(echo "$link" | sed -E 's|^\w+://||g;s|[/:]|-|g;s:-+:-:g;s:-$::g')"
+		else
+			name="$dir/$(basename "$link" | sed 's:\?.+$::')"
+		fi
 		[ $testing = true ] && {
-			echo "arg: '$link'" >&2
-			echo "name: '$name'" >&2
+			error "arg: '$link'"
+			error "name: '$name'"
 		}
 
 		if [ -e "$name" ]; then
@@ -115,7 +162,7 @@ load() {
 				continue
 			}
 			if [ $read = false ]; then
-				echo "already have '$link'" >&2
+				error "already have '$link'"
 			fi
 		else
 			get "$link" "$name"
@@ -129,7 +176,7 @@ load() {
 	done
 }
 
-[ $testing = true ] && echo "$args" >&2
+[ $testing = true ] && error "$args"
 
 echo "$args" | sed "s:^$SEP::g;s:$SEP:\n:g" | while read -r link; do
 	load "$link"
diff --git a/scripts/ghs b/scripts/ghs
--- a/scripts/ghs
+++ b/scripts/ghs
@@ -4,62 +4,75 @@
 
 set -euo pipefail
 
+self="$(basename "$ZSH_ARGZERO")"
+desc="$(cat "$ZSH_ARGZERO" | head -3 | tail -1)"
+
 local _testing=false
 [ $_testing = true ] && set -x
 
 local self=$(basename "$ZSH_ARGZERO")
 helpText() {
-	cat <<-EOF
-		usage: $self [QUERY TERM]...
-		     a script for peeking at github repo READMEs
+	cat <<-EOF | bat -lman
+		usage: $self [MODE] [QUERY TERM]...
 
-		     query terms will be concatenated into a single query
+		$desc
+
+		flags:
+		  -h, --help               print this message and exit
+
+		mode defaults to repo search if not recognized
 	EOF
+	(($#)) || fatal no exit code set for $0
+	exit "$1"
+}
+
+command -v bat &>/dev/null || bat() { less; }
+
+error() {
+	printf '%s:' "$self" >&2
+	printf ' %s' $@ >&2
+	printf '\n' >&2
+}
+
+fatal() {
+	error "$@"
+	exit 1
 }
 
 local args=()
+mode=''
 while (($#)); do
 	case "$1" in
 		-h | --help)
 			helpText
 			exit 0
 			;;
-		-*)
-			echo "unrecognized flag: $1" >&2
-			helpText >&2
-			exit 1
-			;;
-		*)
-			args+="$1"
-			shift
-			;;
+		-*) error "unrecognized flag: $1" && helpText 1 ;;
+		discussions? | issues? | commits? | prs? | repos?) mode="${1%*s}s" ;;
+		*) args+="$1" ;;
 	esac
+	shift
 done
 
-if rg -o '^(code|commits|issues|prs|repos)$' <(echo "${args[1]}") &>/dev/null; then
-	mode="${args[1]}"
-	shift args
-else
-	mode="repos"
-fi
+mode="${mode:-repos}"
 
 tmp="$(mktemp -d)"
 rm -rf "$tmp"
-DIR="$(dirname "$tmp")/$(basename "$ZSH_ARGZERO")"
+DIR="$(dirname "$tmp")/$(realpath "$ZSH_ARGZERO" | xargs -d '\n' basename)"
 [ "$mode" = "repos" -o "$mode" = "prs" -o "$mode" = issues ] && DIR="$DIR/$mode"
 
 [ $_testing = true ] && echo "$DIR"
 [ ! -e "$DIR" ] && mkdir -p "$DIR"
 
 viewer="$(command -v mdv)"
-[ ! -x "$viewer" ] && {
+[ -x "$viewer" ] || {
 	viewer="$(command -v bat) -lmd"
-	[ ! -x "$viewer" ] && {
+	[ -x "$viewer" ] || {
 		viewer="$(command -v cat)"
 	}
 }
 
 case "$mode" in
-	prs | issues | repos) gh search $mode "${args[@]}" | column -t -s $'\t' -H 2 | fzf --tabstop=4 --preview "fetch -r -d '$DIR' -c 'gh ${mode[1, -2]} view' {1} | GH_FORCE_TTY=1 $viewer" | awk '{print $1}' ;;
+	prs | issues | repos) gh search $mode "${args[@]}" | column -t -s $'\t' -H 2 | fzf --tabstop=4 --preview "fetch -r -d '$DIR' -c 'gh ${mode[1,-2]} view' {1} | GH_FORCE_TTY=1 $viewer" | awk '{print $1}' ;;
 	*) gh search $mode "${args[@]}" | column -t -s $'\t' -H 2 | fzf --tabstop=4 | awk '{print $1}' ;;
 esac
diff --git a/scripts/must b/scripts/must
--- a/scripts/must
+++ b/scripts/must
@@ -1,15 +1,87 @@
-#!/bin/env sh
+#!/bin/env bash
 
-sudo=''
-[ "$1" = sudo ] && {
-	sudo=pkexec
-	shift
+# run a command until it exits with status 0
+
+self="$(basename "$0")"
+desc="$(realpath "$0" | xargs cat | head -3 | tail -1)"
+
+error() {
+	printf '%s:' "$self"
+	# shellcheck disable=SC2068
+	printf ' %s' $@
+	printf '\n'
 }
 
+fatal() {
+	error "$@"
+	exit 1
+}
+
+help() {
+	cat <<-eof | bat -lmd
+		usage: $self [arg]...
+
+		$desc
+
+		flags:
+		  -h, --help          print this message and exit
+		  
+	eof
+	(($#)) || fatal no exit code given to helper
+	# shellcheck disable=SC2086
+	exit $1
+}
+
+is_assignment() {
+	local arg="$1"
+	if [[ $arg =~ ^[a-zA-Z_][a-zA-Z0-9_]*=[^=]*$ ]]; then
+		if [[ ! $arg =~ [[:space:]] ]]; then
+			return 0
+		fi
+	fi
+	return 1
+}
+
+flagged=false
 count=0
-while ! $sudo "$@"; do
+args=()
+vars=()
+cmd=""
+sudo=false
+
+while (($#)); do
+	$flagged || {
+		case "$1" in
+			--help | -h*) help 0 ;;
+			*) ;;
+		esac
+	}
+
+	if is_assignment "$1"; then
+		vars+=("$1")
+	else
+		if [ -z "$cmd" ]; then
+			case "$1" in
+				sudo | pkexec) sudo=true ;;
+				*) cmd="$1" ;;
+			esac
+		else
+			args+=("$1")
+		fi
+	fi
+
+	flagged=true
+	shift
+done
+
+if $sudo; then
+	full=(pkexec env "${vars[@]}" "$cmd" "${args[@]}")
+else
+	full=(env "${vars[@]}" "$cmd" "${args[@]}")
+fi
+
+while ! "${full[@]}"; do
 	count=$((count + 1))
 done
-if ! [ $count -eq 0 ]; then
-	echo "Command succeeded after $count retries."
-fi
+
+[ $count = 0 ] || echo "Command succeeded after $count retries."
diff --git a/scripts/query b/scripts/query
--- a/scripts/query
+++ b/scripts/query
@@ -4,32 +4,121 @@
 
 set -euopipefail
 
-testing=false
-[ $testing = true ] && set -x
+self="$(basename "$ZSH_ARGZERO")"
+desc="$(cat "$ZSH_ARGZERO" | head -3 | tail -1 | sed 's:^#\s*::')"
 
-fn() {
-	local query=""
-	local browser="$(xdg-settings get default-web-browser | awk -F. '{print $1}')"
-	[ $# -gt 0 ] && {
-		case "$1" in
-			ff | firefox)
-				browser="firefox"
-				shift
-				;;
-			ch | chromium)
-				browser="chromium"
-				shift
-				;;
-			*)
-				query="$(echo "$@")"
-				break
-				;;
-		esac
-	}
-	[ -z "$query" ] && query="$(xclip -o -selection primary 2>/dev/null || xclip -o -selection clipboard 2>/dev/null || exit 1)"
-	printf 'https://duckduckgo.com?q=%s' "$query" | sed -E 's/\s+/%20/g' | xargs -I{} $browser '{}'
-	return $?
+testing=false
+$testing && set -x
+
+typeset -A engineTable=(
+	[duckduckgo]=https://duckduckgo.com
+	[claude]=https://claude.ai/new
+)
+
+typeset -A aliasTable=(
+	[ddg]=duckduckgo
+	[c]=claude
+)
+
+browser="$(xdg-settings get default-web-browser | awk -F. '{print $1}')"
+engine=duckduckgo
+selection="primary"
+query=()
+prompt=false
+
+command -v bat &>/dev/null || bat() { less; }
+
+error() {
+	printf '%s:' "$self"
+	printf ' %s' $@
+	printf '\n'
 }
 
-fn "$@"
+fatal() {
+	error "$@"
+	exit 1
+}
+
+help_text() {
+	cat <<-eof | bat -lman
+		usage: $self [FLAG]... [SEARCH_TERM]...
+
+		$desc
+
+		flags:
+		  -h, --help          print this message and exit
+		  -b, --browser       set the name of the executable to invoke for the browser (default: $browser)
+		  -e, --engine        set the name of the executable to invoke for the browser (default: $browser)
+		  -s, --source        xclip source to read input from (default: $selection)
+		  -p, --prompt        create a popup that prompts for input
+	eof
+	(($#)) || fatal no exit code specified for help text
+	exit $1
+}
+
+while (($#)); do
+	case "$1" in
+		-h | --help) help_text 0 ;;
+		-p | --prompt) prompt=true ;;
+		-p*) prompt=true && argv[1]="-${1#-f}" && continue ;;
+		-s | --sel | --selection)
+			selection="$2"
+			shift
+			;;
+		-s*) selection="${1#-s}" ;;
+		-b | --browser)
+			browser="$2"
+			shift
+			;;
+		-b*) browser="${1#-b}" ;;
+		-e | --engine) engine="$2" && shift ;;
+		-e*) engine="${1#-e}" ;;
+		-*) fatal unexpected arg: "'$1'" ;;
+		*) query+=("$1") ;;
+	esac
+	shift
+done
+
+# TODO engine validation: skipping for now in the interest of flexibility
+# [ -n "${engineTable[$engine]}" ] || [ -n "${engineTable[${aliasTable[$engine]}]}" ] || fatal unsupported engine: "$engine"
+if [ -n "${engineTable[$engine]}" ]; then
+	engine="${engineTable[$engine]}"
+elif [ -n "${engineTable[${aliasTable[$engine]}]}" ]; then
+	engine="${engineTable[${aliasTable[$engine]}]}"
+elif [ -z "$engine" ]; then
+	fatal no engine specified
+fi
+
+fn() {
+	local search=''
+	if (($#)); then
+		# search="$(printf 'https://duckduckgo.com?q=%s' "$(xclip -o -selection $selection | sed -E 's/\s+/%20/g')")"
+		search="$*"
+	else
+		search="$(xclip -o -selection $selection)"
+	fi
+	# echo "$@"
+	case "$search" in
+		http://* | https://* | file://*) ;;
+		*)
+			search="$(printf '%s?q=%s' "$engine" "$search" | sed -E 's/\s+/%20/g')"
+			;;
+	esac
+	echo "$search"
+	$browser "$search"
+}
+
+if $prompt; then
+	text="$(zenity --entry --title "$browser($selection)" --text "wha blo?")"
+	((${#text})) || exit 1
+	fn "$text"
+elif ((${#query})); then
+	fn "$(
+		printf '%s' "${query[1]}"
+		((${#query[2,-1]})) && printf ' %s' ${query[2,-1]}
+	)"
+else
+	fn "$(xclip -o -selection $selection)"
+fi
+
 exit $?
diff --git a/scripts/xQ b/scripts/xQ
--- a/scripts/xQ
+++ b/scripts/xQ
@@ -1,8 +1,23 @@
-#!/bin/env bash
+#!/bin/env zsh
 
-# query xbps
+# query xbps and choose packages from fzf
 
 set -euo pipefail
+
+self="$(basename "$ZSH_ARGZERO")"
+desc="$(cat "$ZSH_ARGZERO" | head -3 | tail -1)"
+
+error() {
+	printf '%s:' "$self" >&2
+	# shellcheck disable=SC2068
+	printf ' %s' $@ >&2
+	printf '\n' >&2
+}
+
+fatal() {
+	error "$@"
+	exit 1
+}
 
 testing=fale
 [ $testing = true ] && set -x
@@ -21,38 +36,102 @@ need awk || { need gawk && alias awk=gawk; }
 need sed grep fzf
 
 raw=false
-tmp=""
-choices=""
+yes=false
+tmp=()
+
+command -v bat &>/dev/null || bat() { less; }
+
+help_info() {
+	cat <<-eof | bat -lman
+		usage: $self [FLAG]... [PACKAGE]...
+
+		$desc
+
+		flags:
+		  -h, --help            print this message and exit
+		  -r, --raw             print results and exit
+		  -y, --yes             autoaccept installation
+	eof
+	(($#)) || fatal internal: no exit code given to helper
+	exit "$1"
+}
 
 while [ $# -gt 0 ]; do
 	case "$1" in
+		-h* | --help) help_info 0 ;;
 		-r | --raw) raw=true ;;
+		-y | --yes) yes=true ;;
+		-y*)
+			yes=true
+			argv[1]="${1##-y}"
+			continue
+			;;
+		-r*)
+			raw=true
+			argv[1]="${1##-r}"
+			continue
+			;;
 		-*) echo unrecognized flag: "$1" && exit 1 ;;
-		*) tmp="$tmp $1" ;;
+		*) tmp+=("$1") ;;
 	esac
 	shift
 done
 
 # shellcheck disable=SC2086
-set -- $tmp
+set -- "${tmp[@]}"
 
+# error "$@"
 search() {
-	xbps-query -Rs "$1" | grep -E "] (\w+(-)?)*$1((-)?\w+)*-" | grep "$1"
+	{ xbps-query -Rs "$1" | grep -E "$(printf '] (\w+(-)?)*%s((-)?\w+)*-' "$1")" | grep -E "$1"; } || true
 }
 
-if [ $raw = false ]; then
-	choices="$(for arg in "$@"; do
-		search "$arg"
-	done | sort -h | column -ts $'\t' | fzf | awk '{print $2}' | sed -E 's/-[0-9_.]+$//')"
-else
+cleanup() {
+	awk '{ lines[NR]=$0; status[NR]=$1; name[NR]=$2; $1=$2=""; desc[NR]=substr($0,3)
+          if (length(name[NR]) > max) max=length(name[NR]) }
+        END { for (i=1;i<=NR;i++) printf "%s\t%-*s\t%s\n", status[i], max, name[i], desc[i] }
+    ' | column -ts $'\t'
+}
+
+choices=()
+$raw && {
+	# error raw
 	for arg in "$@"; do
+		echo "err: $arg" >/dev/stderr
 		search "$arg"
+	done |
+		sort -h |
+		cleanup |
+		uniq
+	exit $?
+}
+
+tmp="$(mktemp)" || fatal "couldn't source bindings"
+grep '^export' "$DOTFILES/.zshenv" | grep -E 'FZF|SKIM' >"$tmp"
+. "$tmp"
+rm "$tmp"
+
+for arg in "$@"; do
+	search "$arg"
+done |
+	sort -h |
+	cleanup |
+	uniq |
+	fzf -n2 |
+	awk '{print $2}' |
+	sed -E 's:-[0-9_\.]+$::' |
+	while read -r pkg; do
+		choices+=("$pkg")
 	done
-fi
 
 code=$?
 
-[ -n "$choices" ] || exit $code
+((${#choices})) || exit $code
 
-echo installing: "$choices"
-eval 'sudo xbps-install -Su $choices'
+if $yes; then
+	yes='-y'
+else
+	yes=''
+fi
+
+echo installing: "${choices[@]}" >&2
+while ! pkexec xbps-install -Su $yes "${choices[@]}"; do :; done
diff --git a/scripts/xu b/scripts/xu
--- a/scripts/xu
+++ b/scripts/xu
@@ -1,5 +1,19 @@
 #!/bin/env sh
 
+self="$(basename "$0")"
+
+error() {
+	printf '%s:' "$self" >&2
+	# shellcheck disable=SC2068
+	printf ' %s' $@ >&2
+	printf '\n' >&2
+}
+
+fatal() {
+	error "$@"
+	exit 1
+}
+
 if [ -x "$(command -v sk)" ]; then
 	finder=sk
 elif [ -x "$(command -v fzf)" ]; then
@@ -9,4 +23,15 @@ else
 	exit 1
 fi
 
-sudo xbps-install -Syu $(xbps-install -nSu | cut -f1 -d' ' | sed 's/-[^-]*$//g' | $finder | tr '\n' ' ')
+tmp="$(mktemp)" || fatal "couldn't source bindings"
+grep '^export' "$DOTFILES/.zshenv" | grep -E 'FZF|SKIM' >"$tmp"
+. "$tmp"
+rm "$tmp"
+
+# shellcheck disable=SC2046
+choices="$(xbps-install -nSu | cut -f1 -d' ' | sed 's/-[^-]*$//g' | $finder | tr '\n' ' ')"
+
+[ -n "$choices" ] || exit
+
+# shellcheck disable=SC2086
+while ! pkexec xbps-install -Syu $choices; do :; done
